{{- if .Values.clusterStorage.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "kubecost.clusterStorage.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.clusterStorage.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubecost.clusterStorage.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: tcp-api
      port: 9006
      targetPort: 9006
{{- end }}