global:
  clusterId: helm-testing
  federatedStorage:
    existingSecret: federated-storage-config
aggregator:
  enabled: true
  aggregatorDbStorage:
    storageRequest: 10Gi
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi
cloudCost:
  enabled: true
  cloudIntegrationSecret: cloud-integration
finopsagent:
  enabled: false
