{{- if ((.Values.kubecostProductConfigs).actions).enabled }}
{{- if ((.Values.kubecostProductConfigs).actions).storageConfig }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: actions-store
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  actions-store.yaml: {{ ((.Values.kubecostProductConfigs).actions).storageConfig | b64enc }}
{{- end }}
{{- end }}