apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-export-bucket-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  federated-store.yaml: {{ (include "kubecost.exportBucket.config" . ) | b64enc | quote }}

