{{- if not (.Values.global.exportBucket).existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-export-bucket-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  {{- include "kubecost.exportBucket.fileName" . | nindent 2}}: {{ (include "kubecost.exportBucket.config" . ) | b64enc | quote }}
{{- end }}
