{{- if and (not .Values.kubecost.plugins.existingCustomSecret.enabled) .Values.kubecost.plugins.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubecost.plugins.secretName }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  {{- range $key, $config := .Values.kubecost.plugins.configs }}
  {{ $key }}_config.json:
    {{ $config | b64enc | indent 4}}
  {{- end }}
{{- end }}
