{{- if not (.Values.global.storageConfig).existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-storage-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  {{- include "kubecost.storageConfig.fileName" . | nindent 2}}: {{ (include "kubecost.storageConfig.config" . ) | b64enc | quote }}
{{- end }}
