{{- if (.Values.clusterController).enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecost.clusterControllerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
{{- end }}