global:
  clusterId: helm-testing
storageConfig:
  secret:
    config: |-
      type: S3
      config: intentionally-invalid
      bucket: "kubecost-helm-testing-metrics"
        endpoint: "s3.amazonaws.com"
        region: "us-east-2"
