{
 "title": "Kubecost Network Costs Metrics",
 "description": "https://www.ibm.com/docs/en/kubecost/self-hosted/2.x?topic=configuration-network-cost",
 "tags": [ "kubecost" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "aggregation",
    "query": "cluster_id, namespace, pod_name"
   },
   { "name": "cluster", "query": { "query": "label_values(cluster_id)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=~\"$cluster\"}, namespace) "
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kubecost_pod_network_egress_bytes_total{cluster_id=~\"$cluster\", namespace=~\"$namespace\"},pod_name)"
    }
   },
   { "name": "filter" },
   {
    "name": "service",
    "query": {
     "query": "label_values(kubecost_pod_network_egress_bytes_total{namespace=~\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Data Transfers (negative is egress data)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "All Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(kubecost_pod_network_ingress_bytes_total\n {namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", service=~\"$service\"}\n [1h]\n ))\nby($aggregation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum(increase(kubecost_pod_network_egress_bytes_total\n {namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", service=~\"$service\"}\n [1h]\n ))\nby($aggregation) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Data",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(kubecost_pod_network_ingress_bytes_total\n  {internet=\"true\", namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", service=~\"$service\"}\n  [1h]\n))\nby($aggregation) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum(increase(kubecost_pod_network_egress_bytes_total\n    {internet=\"true\", namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", service=~\"$service\"}\n    [1h]))\nby($aggregation) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross Region Data",
   "type": "timeseries",
   "description": "Cross region and cross zone subnets must be defined via the configMap. \nSee: \n<https://www.ibm.com/docs/en/kubecost/self-hosted/2.x?topic=configuration-network-cost>",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(kubecost_pod_network_ingress_bytes_total\n    {internet=\"false\",namespace=~\"$namespace\",cluster_id=~\"$cluster\",pod_name=~\"$pod_name\", sameRegion=\"false\",sameZone=\"false\", service=~\"$service\"}\n    [1h]))\nby($aggregation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum(increase(kubecost_pod_network_egress_bytes_total\n    {internet=\"false\", namespace=~\"$namespace\",cluster_id=~\"$cluster\",pod_name=~\"$pod_name\",sameRegion=\"false\", sameZone=\"false\", service=~\"$service\"}\n    [1h]))\nby($aggregation) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cross Zone Data",
   "type": "timeseries",
   "description": "Cross region and cross zone subnets must be defined via the configMap. \nSee: \n<https://www.ibm.com/docs/en/kubecost/self-hosted/2.x?topic=configuration-network-cost>",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(kubecost_pod_network_ingress_bytes_total\n  {internet=\"false\", namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", sameRegion=\"true\", sameZone=\"false\", service=~\"$service\"}\n  [1h]))\nby($aggregation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "- sum(increase(kubecost_pod_network_egress_bytes_total\n  {internet=\"false\", namespace=~\"$namespace\", cluster_id=~\"$cluster\", pod_name=~\"$pod_name\", sameRegion=\"true\", sameZone=\"false\", service=~\"$service\"}\n  [1h]))\nby($aggregation)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}