global:
  storageConfig:
    existingSecret: storage-config
kubecostProductConfigs:
  clusterName: CLUSTER_NAME
#cloudCost:
#  cloudIntegrationSecret: cloud-integration
serviceAccount:  # this example uses AWS IRSA, which creates a service account with rights to the s3 bucket. If using keys+secrets in the export bucket, set create: true
  create: true
networkCosts:
  # optional, see: https://www.ibm.com/docs/en/kubecost/self-hosted/2.x?topic=configuration-network-cost
  enabled: true
  config:
    services:
      # set the appropriate cloud provider to true
      amazon-web-services: true
      # google-cloud-services: true
      # azure-cloud-services: true
aggregator:
  resources:
    limits:
      memory: 10Gi
    requests:
      cpu: 2000m
      memory: 10Gi
