global:
  imageRegistry: public.ecr.aws
frontend:
  image:
    repository: kubecost/frontend

aggregator:
  image:
    repository: kubecost/cost-model

forecasting:
  image:
    repository: kubecost/kubecost-modeling
    tag: v0.1.28

networkCosts:
  image:
    repository: kubecost/kubecost-network-costs

clusterController:
  image:
    repository: kubecost/cluster-controller

finops-agent:
  image:
    repository: kubecost/agent

reporting:
  productAnalytics: false
