{{- if and (.Values.clusterController).enabled .Values.clusterController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecost.clusterController.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "kubecost.commonLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.clusterController.serviceAccount.annotations }}
    {{- toYaml .Values.clusterController.serviceAccount.annotations | nindent 4 }}
  {{- else }}
    {{-  toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
