{{- if .Values.saml.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.saml.authSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
stringData:
  {{- $secretName := .Values.saml.authSecretName | default "kubecost-saml-secret" }}
  {{- $authSecretParams := dict "root" . "value" .Values.saml.authSecret "field" ".Values.saml.authSecret" "secretName" $secretName "secretKey" "clientSecret" }}
  clientSecret: {{ include "kubecost.authSecretValue" $authSecretParams }}
{{- end }}
