{{- if and (eq (include "kubecost.rbacTeams.enabled" .) "true") (not ((.Values.kubecostRbacSecret).existingSecret)) }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace "kubecost-rbac-secret") -}}
{{- $existingKey := "" -}}
{{- if and $existing $existing.data (hasKey $existing.data "key") -}}
{{-   $existingKey = index $existing.data "key" | b64dec -}}
{{- end -}}
{{- $explicitKey := "" -}}
{{- if .Values.oidc.enabled -}}
{{-   $explicitKey = .Values.oidc.authSecret | default "" -}}
{{- end -}}
{{- if and (not $explicitKey) .Values.saml.enabled -}}
{{-   $explicitKey = .Values.saml.authSecret | default "" -}}
{{- end -}}
{{- $key := coalesce $explicitKey $existingKey (randAlphaNum 32) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubecost-rbac-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
stringData:
  key: {{ $key | quote }}
{{- end }}
