federatedETL:
  agentOnly: true
global:
  clusterId: YOUR_CLUSTER_ID
  ## either method of configuring federated storage is valid (secret or yaml block)
  federatedStorage:
    config: |-
      type: S3
      config:
        bucket: YOUR_BUCKET_NAME
        endpoint: s3.amazonaws.com
        region: us-west-2
        # access_key: YOUR_ACCESS_KEY
        # secret_key: YOUR_SECRET_KEY
    existingSecret: ""

## When using assumed roles to access the bucket, the same service account that is used
## by the cost-analyzer pod can be used for the new finops-agent.
## Below- note that serviceAccount and finopsagent are top level keys (no space before them).
# serviceAccount:  ## used by cost-analyzer
#   create: false
#   name: ""  ## keep existing values
#   annotations: {}  ## keep existing values
# finopsagent:  ## used by finopsagent
#   serviceAccount:
#     create: false
#     name: ""
#     annotations: {}
#   persistence:
#     enabled: true
#     storageClass: ""
#     size: 8Gi
