{{- if or (.Values.cloudCost).cloudIntegrationJSON (.Values.kubecostProductConfigs).cloudIntegrationJSON -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kubecost.cloudCost.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  cloud-integration.json: {{ include "kubecost.cloudCost.cloudIntegrationJSON" . | replace "\n" "" | b64enc }}
{{- end -}}
