{{- if and .Values.cloudCost.serviceAccount.create (not .Values.cloudCost.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubecost.cloudCost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.cloudCost.commonLabels" . | nindent 4 }}
{{- with .Values.cloudCost.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- else }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
