{{- if and (.Values.cloudCost).enabled .Values.cloudCost.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecost.cloudCost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "kubecost.commonLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.cloudCost.serviceAccount.annotations }}
    {{- toYaml .Values.cloudCost.serviceAccount.annotations | nindent 4 }}
  {{- else }}
    {{-  toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
