enterpriseCustomPricing:
  enabled: true

  # kubectl create configmap -n kubecost kubecost-enterprise-pricing --from-file spec.csv
  # defaults to "kubecost-enterprise-pricing" but can be changed
  configMapName: kubecost-enterprise-pricing
  
  # The file name (e.g. spec.csv) needs to match the file name used to make the ConfigMap (above)
  location:
    URI: /var/enterprise-pricing/spec.csv

  # By default, enterprise custom pricing takes effect moving forward from when
  # it is enabled. To price all historic data according to the given pricing
  # spec, set "applyRetroactively" to true, below.
  # applyRetroactively: true

# This value will only be required until the release of Kubecost 3.0.0, at which point it will be removed
kubecostAggregator:
  useDBv3: true
