# This Helm values file is a modified version of `values-openshift.yaml`.
# The primary difference is that this file is configured to disable the Kubecost-bundled Prometheus, and instead leverage the Prometheus instance that is typically pre-installed in OpenShift clusters.
global:
  prometheus:
    enabled: false  # Kubecost depends on Prometheus data, it is not optional. When enabled: false, Prometheus will not be installed and you must configure your in-cluster Prometheus to scrape kubecost as well as provide the fqdn below. -- Warning: Before changing using this setting, please read to understand the risks https://docs.kubecost.com/install-and-configure/install/custom-prom
    fqdn: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091  # example address of a Prometheus to connect to. Include protocol (http:// or https://) Ignored if enabled: true
    insecureSkipVerify: false  # If true, kubecost will not check the TLS cert of prometheus
    kubeRBACProxy: true # If true, kubecost will use kube-rbac-proxy to authenticate with in cluster Prometheus for openshift
  grafana:
    enabled: false  # If false, Grafana will not be installed
    domainName: grafana.grafana
    proxy: false

  platforms:
    # Deploying to OpenShift (OCP) requires enabling this option.
    openshift:
      enabled: true  # Deploy Kubecost to OpenShift.
      createMonitoringClusterRoleBinding: true  # Create a ClusterRoleBinding to allow using in-cluster Prometheus or Thanos.
      createMonitoringResourceReaderRoleBinding: true  # Create a Role and Role Binding to allow in-cluster Prometheus or Thanos to list and watch resources. This will be necessary if you are not using bundled prometheus and need to add scrape config for resources.
      monitoringServiceAccountName: prometheus-k8s  # Name of the service account to bind to the Resource Reader Role Binding.
      monitoringServiceAccountNamespace: openshift-monitoring  # Namespace of the service account to bind to the Resource Reader Role Binding.

      # Create Security Context Constraint resources for the DaemonSets requiring additional privileges.
      scc:
        networkCosts: false  # Creates an SCC for Kubecost network-costs. This requires network-costs be enabled.
      # When OpenShift is enabled, the following securityContext will be applied to all resources unless they define their own.
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

# networkCosts:
#   enabled: false  # Enable network costs.
# prometheus:
#   nodeExporter:
#     enabled: true  # Enable Prometheus Node Exporter.
serviceMonitor:
  enabled: true
  # networkCosts:
  #   enabled: false

prometheusRule:
  enabled: true
