{{- if (.Values.cloudCost).enabled }}

{{/*
  TODO I don't think this is actually true but we could just force this
  A cloud integration secret is required for cloud cost to function as a dedicated pod.
  UI based configuration is not supported for cloud cost with aggregator.
*/}}
{{- if (.Values.cloudCost).enabled }}
{{- if not ( or (.Values.cloudCost).cloudIntegrationSecret (.Values.cloudCost).cloudIntegrationJSON ) }}
{{- fail "\n\nA cloud-integration secret is required when using the aggregator statefulset and cloudCost is enabled." }}
{{- end }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudCost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudCost.commonLabels" . | nindent 4 }}
    {{- with .Values.global.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.aggregator.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudCost.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-cost
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: cloud-cost
        {{- with .Values.global.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.global.podAnnotations}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configs: {{ include "configsChecksum" . }}
    spec:
      {{- if .Values.global.platforms.openshift.enabled }}
      securityContext:
      {{- toYaml .Values.global.platforms.openshift.securityContext | nindent 8 }}
      {{- else if .Values.global.securityContext }}
      securityContext:
      {{- toYaml .Values.global.securityContext | nindent 8 }}
      {{- else }}
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ template "cloudCost.serviceAccountName" . }}
      volumes:
        - name: export-bucket-config
          secret:
            defaultMode: 420
            secretName: {{ include "kubecost.exportBucket.secretName" . }}
        {{- if or (.Values.cloudCost).cloudIntegrationSecret (.Values.cloudCost).cloudIntegrationJSON }}
        - name: cloud-integration
          secret:
            secretName: {{ include "kubecost.cloudCost.secretName" . }}
            items:
              - key: cloud-integration.json
                path: cloud-integration.json
        {{- end }}
        {{/* Despite the name, this is not persistent-configs.
            The name is for compatibility with single-pod install.
            All data stored here is ephemeral, and does not require persistence. */}}
        - name: persistent-configs
          emptyDir: {}
        {{- if .Values.kubecostModel.plugins.enabled  }}
        {{- if .Values.kubecostModel.plugins.install.enabled}}
        - name: install-script
          configMap:
            name: {{ template "cost-analyzer.fullname" . }}-install-plugins
        {{- end }}
        - name: plugins-dir
          emptyDir: {}
        {{- if and (not .Values.kubecostModel.plugins.existingCustomSecret.enabled) .Values.kubecostModel.plugins.secretName }}
        - name: plugins-config
          secret:
            secretName: {{ .Values.kubecostModel.plugins.secretName }}
            items:
             {{- range $key, $config := .Values.kubecostModel.plugins.enabledPlugins }}
              - key: {{ $config }}_config.json
                path: {{ $config }}_config.json
            {{- end }}
        {{- end }}
        {{- if .Values.kubecostModel.plugins.existingCustomSecret.enabled }}
        - name: plugins-config
          secret:
            secretName: {{ .Values.kubecostModel.plugins.existingCustomSecret.name }}
            items:
            {{- range $key, $config := .Values.kubecostModel.plugins.enabledPlugins }}
              - key: {{ $config }}_config.json
                path: {{ $config }}_config.json
            {{- end }}
        {{- end }}
        - name: tmp
          emptyDir: {}
        {{- end }}
        {{- if .Values.global.updateCaTrust.enabled }}
        - name: ca-certs-secret
          {{- if .Values.global.updateCaTrust.caCertsSecret }}
          secret:
            defaultMode: 420
            secretName: {{ .Values.global.updateCaTrust.caCertsSecret }}
          {{- else }}
          configMap:
            name: {{ .Values.global.updateCaTrust.caCertsConfig }}
          {{- end }}
        - name: ssl-path
          emptyDir: {}
        {{- end }}
        {{- if (.Values.cloudCost).extraVolumes }}
        {{- toYaml (.Values.cloudCost).extraVolumes | nindent 8 }}
        {{- end }}
      initContainers:
      {{- if (and .Values.kubecostModel.plugins.enabled .Values.kubecostModel.plugins.install.enabled )}}
      - name: plugin-installer
        image: {{ .Values.kubecostModel.plugins.install.fullImageName }}
        command: ["sh", "/install/install_plugins.sh"]
        {{- with .Values.kubecostModel.plugins.install.securityContext }}
        securityContext: {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: install-script
            mountPath: /install
          - name: plugins-dir
            mountPath: {{ .Values.kubecostModel.plugins.folder }}
      {{- end }}
      {{- if .Values.global.updateCaTrust.enabled }}
      - name: update-ca-trust
        image: {{ include "cost-model.image" . | trim | quote}}
        {{- if .Values.kubecostModel.imagePullPolicy }}
        imagePullPolicy: {{ .Values.kubecostModel.imagePullPolicy }}
        {{- else }}
        imagePullPolicy: Always
        {{- end }}
        {{- with .Values.global.updateCaTrust.securityContext }}
        securityContext: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.global.updateCaTrust.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        command:
          - 'sh'
          - '-c'
          - >
            mkdir -p /etc/pki/ca-trust/extracted/{edk2,java,openssl,pem};
            /usr/bin/update-ca-trust extract;
        volumeMounts:
          - name: ca-certs-secret
            mountPath: {{ .Values.global.updateCaTrust.caCertsMountPath | quote }}
          - name: ssl-path
            mountPath: "/etc/pki/ca-trust/extracted"
            readOnly: false
      {{- end}}
      containers:
        - name: cloud-cost
          {{- if .Values.kubecostModel }}
          {{- if .Values.aggregator.fullImageName }}
          image: {{ .Values.aggregator.fullImageName }}
          {{- else if .Values.kubecostModel.fullImageName }}
          image: {{ .Values.kubecostModel.fullImageName }}
          {{- else if .Values.imageVersion }}
          image: {{ .Values.kubecostModel.image }}:{{ .Values.imageVersion }}
          {{- else if eq "development" .Chart.AppVersion }}
          image: gcr.io/kubecost1/cost-model-nightly:latest
          {{- else }}
          image: {{ .Values.kubecostModel.image }}:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          {{- else }}
          image: gcr.io/kubecost1/cost-model:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          {{- if (.Values.cloudCost).readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9005
            initialDelaySeconds: {{ (.Values.cloudCost).readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ (.Values.cloudCost).readinessProbe.periodSeconds }}
            failureThreshold: {{ (.Values.cloudCost).readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.aggregator.imagePullPolicy }}
          imagePullPolicy: {{ .Values.aggregator.imagePullPolicy }}
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          args: ["cloud-cost"]
          ports:
            - name: tcp-api
              containerPort: 9005
              protocol: TCP
          resources:
            {{- toYaml (.Values.cloudCost).resources | nindent 4 }}
          securityContext:
            {{- if .Values.global.containerSecurityContext }}
            {{- toYaml .Values.global.containerSecurityContext | nindent 4 }}
            {{- end }}
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
            - name: export-bucket-config
              mountPath: /var/configs/export
              readOnly: true
          {{- if or (.Values.cloudCost).cloudIntegrationSecret (.Values.cloudCost).cloudIntegrationJSON }}
            - name: cloud-integration
              mountPath: /var/configs/cloud-integration
          {{- end }}
            {{- if .Values.kubecostModel.plugins.enabled }}
            - mountPath: {{ .Values.kubecostModel.plugins.folder }}
              name: plugins-dir
              readOnly: false
            - name: tmp
              mountPath: /tmp
            - mountPath: {{ $.Values.kubecostModel.plugins.folder }}/config
              name: plugins-config
              readOnly: true
            {{- end }}
            {{- if .Values.global.updateCaTrust.enabled }}
            - name: ca-certs-secret
              mountPath: {{ .Values.global.updateCaTrust.caCertsMountPath | quote }}
            - name: ssl-path
              mountPath: "/etc/pki/ca-trust/extracted"
              readOnly: false
            {{- end }}
          {{- if (.Values.cloudCost).extraVolumeMounts }}
            {{- toYaml (.Values.cloudCost).extraVolumeMounts | nindent 4 }}
          {{- end }}
          env:
            - name: CONFIG_PATH
              value: /var/configs/
            - name: EXPORT_BUCKET_CONFIG_FILE
              value: /var/configs/export/{{- include "kubecost.exportBucket.fileName" .}}
            - name: ETL_DAILY_STORE_DURATION_DAYS
              value: {{ (quote .Values.kubecostModel.etlDailyStoreDurationDays) }}
            - name: CLOUD_COST_REFRESH_RATE_HOURS
              value: {{ (.Values.cloudCost).refreshRateHours | default 6 | quote }}
            - name: CLOUD_COST_QUERY_WINDOW_DAYS
              value: {{ (.Values.cloudCost).queryWindowDays | default 7 | quote }}
            - name: CLOUD_COST_RUN_WINDOW_DAYS
              value: {{ (.Values.cloudCost).runWindowDays | default 3 | quote }}
            - name: CUSTOM_COST_ENABLED
              value: {{ .Values.kubecostModel.plugins.enabled | quote }}
            {{- range $key, $value := (.Values.cloudCost).env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.systemProxy.enabled }}
            - name: HTTP_PROXY
              value: {{ .Values.systemProxy.httpProxyUrl }}
            - name: http_proxy
              value: {{ .Values.systemProxy.httpProxyUrl }}
            - name: HTTPS_PROXY
              value: {{ .Values.systemProxy.httpsProxyUrl }}
            - name: https_proxy
              value: {{ .Values.systemProxy.httpsProxyUrl }}
            - name: NO_PROXY
              value: {{ .Values.systemProxy.noProxy }}
            - name: no_proxy
              value: {{ .Values.systemProxy.noProxy }}
            {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $.Values.imagePullSecrets }}
        - name: {{ .name }}
      {{- end }}
    {{- end }}
      {{- if ((.Values.aggregator).priority).enabled }}
      {{- if .Values.aggregator.priority.name }}
      priorityClassName: {{ .Values.aggregator.priority.name }}
      {{- else }}
      priorityClassName: {{ template "cost-analyzer.fullname" . }}-aggregator-priority
      {{- end }}
      {{- end }}

      {{- with (.Values.cloudCost).nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.cloudCost).tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.cloudCost).affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
