{{- if ((.Values.kubecostProductConfigs).actions).enabled }}
{{- if ((.Values.kubecostProductConfigs).actions).exportBucket }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-actions-export-bucket-config
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  actions-store.yaml: {{ ((.Values.kubecostProductConfigs).actions).exportBucket | b64enc }}
{{- end }}
{{- end }}