global:
  federatedStorage:
    config: |-
      type: S3
      config:
        bucket: "kubecost-helm-testing-metrics"
        endpoint: "s3.amazonaws.com"
        region: "us-east-2"
  clusterId: helm-testing
