kubecostModel:
  federatedStorageConfig: |-
    type: S3
    config:
      bucket: "kubecost-helm-testing-metrics"
      endpoint: "s3.amazonaws.com"
      region: "us-east-2"
kubecostProductConfigs:
  clusterName: helm-testing
finops-agent:
  enabled: true
  clusterId: cluster-one
