name: Chart build and test 3.x

on:
  workflow_dispatch: {}
  # Normally using pull_request_target along with checking out the ref of the PR is not
  # a good idea, but this is low risk since it's a Helm chart repo.
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

  # Uncomment this if you need to actively test this workflow from a PR draft
  pull_request:
    branches:
      - develop

# Prevents multiple runs of the same workflow on the same branch from executing 
# simultaneously. Saves resources.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Add finops-agent-chart
        uses: actions/checkout@v5
        with:
          repository: kubecost/finops-agent-chart
          ref: main
          path: finops-agent-chart

      # Lint all chart values including those in the ci directory.
      - name: Run chart-testing (lint)
        run: |
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo update
          ct lint --chart-dirs=kubecost/ --charts kubecost/ --validate-maintainers=false

      # Build the finops-agent subchart and make it available for the main chart
      # - name: Build finops-agent subchart
      #   run: |
      #     # Package the finops-agent chart
      #     helm dependency build finops-agent-chart/charts/finops-agent
      #     helm package finops-agent-chart/charts/finops-agent
          
      #     # Create charts directory if it doesn't exist
      #     mkdir -p kubecost/charts
          
      #     # Move the packaged chart to the kubecost charts directory
      #     mv finops-agent-*.tgz kubecost/charts/

      # Run `helm template` on the main values file plus all those in the ci directory.
      - name: Helm template
        run: |
          helm template kubecost/ -f .github/ci-helmValues/helmValues-federated-store.yaml \
            --set finops-agent.enabled=false \
            --debug > full.yaml
          directory="kubecost/ci"
          for file in "$directory"/*; do
          if [ -f "$file" ]; then
              echo "Templating file $file"
              helm template kubecost/ -f "$file" --debug >> full.yaml
          fi
          done

      # Run Kubeconform on the combined, templatized output across all tested values stored in `full.yaml`.
      # Ensure all the rendered resources are valid.
      - name: Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: /kubeconform
          args: "-summary -ignore-missing-schemas -output text full.yaml"

  # Test cluster versions.
  deploy-chart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.28
            version: v1.28.15
          - name: v1.29
            version: v1.29.14
          - name: v1.30
            version: v1.30.13
          - name: v1.31
            version: v1.31.12
          - name: v1.32
            version: v1.32.8
          - name: v1.33
            version: v1.33.4
          - name: v1.34
            version: v1.34.0
    needs: test-chart
    name: ${{ matrix.k8s-version.name }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Create KinD cluster
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.20.0
          node_image: kindest/node:${{ matrix.k8s-version.version }}
          kubectl_version: ${{ matrix.k8s-version.version }}

      # Create necessary test files in the cluster. Some configurations of the chart
      # require pre-existing files like Secrets in order for volume mounts to be valid. Without them,
      # Pods won't come up and tests will fail.
      - name: Create kubecost Namespace and test files
        run: |
          kubectl create ns kubecost
          kubectl -n kubecost create -f .github/ci-files

      # Install the chart with default values and check results.
      - name: Install Kubecost chart
        working-directory: ./kubecost
        run: helm install --wait --wait-for-jobs kubecost . -n kubecost --debug
        # run: ct install --namespace kubecost --chart-dirs=kubecost/ --charts kubecost/

      - name: Wait for ready 
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
      
      - name: gather debug info - install 
        if: failure()
        run: |
          kubectl get pods -n kubecost
          kubectl get pods -n kubecost -o yaml
          kubectl get pods -n kubecost -o json
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl -n kubecost describe pods
          kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost

      - name: Run Helm tests 
        run: helm test -n kubecost kubecost

      - name: gather debug info - test
        if: failure()
        run: |
          kubectl get pods -n kubecost
          kubectl get pods -n kubecost -o yaml
          kubectl get pods -n kubecost -o json
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl -n kubecost describe pods
          echo "kubecost logs"
          kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost
          echo "agg logs"
          kubectl -n kubecost logs -l app.kubernetes.io/instance=aggregator
          echo "basic-health logs"
          kubectl -n kubecost logs basic-health

      - name: Uninstall chart
        run: helm uninstall kubecost -n kubecost --no-hooks --wait

      - name: Cleanup all Pods in Kubecost Namespace
        run: kubectl -n kubecost delete deployments,daemonsets,statefulsets,pods --all --force

      # Loops over all the other values files in the ci directory and installs the chart, runs Helm tests, and uninstalls.
      # Additional sleeps seem necessary for the main Kubecost Pod to be completely available, both frontend and backend.
      - name: Install, test, remove chart for other values
        id: loopingtests
        run: |
          directory="kubecost/ci"
          for file in "$directory"/*; do
          if [ -f "$file" ]; then
            echo "### Sleeping for 30 seconds ###"
            sleep 30
            echo "### Performing installation with values from $file ###"
            helm install --wait --wait-for-jobs kubecost kubecost/ -n kubecost -f "$file"
            echo "### Waiting for kubecost Pod readiness. ###"
            kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
            echo "### Sleeping for 60 seconds longer. ###"
            sleep 60
            echo "### [DEBUG] printing debug info ###"
            kubectl -n kubecost get pods
            kubectl get pods -n kubecost -o yaml
            kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
            kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
            kubectl -n kubecost describe pods
            kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost
            echo "### Performing helm tests ###"
            helm test -n kubecost $(helm ls -n kubecost --all --short)
            echo "### Performing uninstallation ###"
            helm uninstall $(helm ls -n kubecost --all --short) -n kubecost --no-hooks --wait
            echo "### Cleaning up all Pods and Pod controllers in Kubecost Namespace ###"
            kubectl -n kubecost delete deployments,daemonsets,statefulsets,pods --all --force
          fi
          done