{{- if .Values.networkCosts -}}
{{- if .Values.networkCosts.enabled -}}
{{- if or .Values.networkCosts.storageConfig .Values.networkCosts.natGatewayConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: network-costs-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.networkCosts.storageConfig }}
  storage.yaml: |
{{ toYaml .Values.networkCosts.storageConfig | nindent 4 }}
{{- end }}
{{- if .Values.networkCosts.natGatewayConfig }}
  nat-gateway.yaml: |
{{ toYaml .Values.networkCosts.natGatewayConfig | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
